# タイトル設定
### titleは必須。sub_titleは任意で、不要な場合はコメントアウトすること。
adv_title: "フェスティバルルミナズム！"
adv_sub_title: "あなたとわたしの物語"
### タイトル画面の背景を指定する。画像はinput/assets/backgrounds/に配置すること。
title_bg_image: "start_1.png"
### タイトルを画像に変更したい場合は下をコメントアウトしてファイル名を入力する。両方コメントアウトした場合はテキストが優先される。
adv_title_image: "start_1"
adv_text_title_off: "true"

# システム設定
localstorage_prefix: "festival_luminasm"
version: "2026.03.18"
music_def_volume: "10"

##  最適化設定
target_size: "1080"
optimization_level: "95"



## カスタム設定
custom_name: "true"

## 色などの設定。sub_colorはグラデーションやアクセントに使われる色
theme_color: "#171717"
sub_color: "#171717"
text_color: "#FFFFFF"

## GoogleFontsのインポートURLを指定する。不要な場合はコメントアウトする。
text_font_importURL: "https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap"





# ブランディング
creator_name: "天波たくみ"
### クレジット欄に記載される。Licenseは任意の指定。
License: "本作品は星海天測団が提供するノベルゲーム生成エンジン、「Luminus Script」を用いて制作されたノベルゲームです。

登場人物はほぼ全て実在のVRChatユーザであり、実在しない場合も第三者の著作物です。

登場する背景画像の多くはVRChatに実在するワールドであり、第三者の著作物です。

登場人物及び背景画像は尊重され、最大限の敬意を向けられる必要があります。

以下の行為は禁止されています。

1. ゲームを再頒布する行為

2. 本ゲームの制作者を騙る行為（自作発言等の禁止）

3. 法律に認められる引用の範囲を超えた行為

4. ゲームに含まれる画像データを抜き出す行為

5. ゲームが使用するLocalStorageのデータやゲーム本体のデータを書き換えて、制作者が意図しない挙動を生じさせる行為。

6. 本作内の画像を用いた登場人物、または第三者の思想・名誉等を害する目的の表現

7. 本作内の画像を用いた過度な暴力表現、グロテスクな描写、または性的表現

8. 本作内の画像を用いた特定の政治・宗教・信条を支持または否定する内容の表現

9. 本作内の画像を用いた反社会的な表現

10. 本作内の画像を用いた第三者の権利を侵害する行為

11. 本作内の画像を用いた商業利用または営利目的

12. 本作内の画像を用いたその他、上記趣旨（4～11）に照らして不適切と判断される内容"


## クレジット欄に記載される。リンク類の設定。不要な場合はコメントアウトする。
# x_account_url: "https://x.com/amanami_takumi2"
# vrchat_account_url: "https://vrchat.com/home/user/usr_dc60d17d-d529-4c3b-8be7-1d259df0227f"
# fediverse_account_url: "https://misskey.seitendan.com/@takumin3211"
web_url: "https://luminasm.seitendan.com"
# booth_url: ""
### タイトル画面の背景を指定する。画像はinput/assets/backgrounds/に配置すること。
favicon_url: "favicon.ico"






# 以下、閲覧注意（不適切単語リストが掲示されている）
























forbidden_word: [死ね,カス,ゴミ,クズ,うんち,チンコ,マンコ,殺す,野獣,淫夢,自民,共産,国民民主,公明,自殺,馬鹿,バカ,性器,性感帯,オナニー,フェラ,クンニ,陰毛,陰茎,包茎,勃起,射精,童貞,子宮,膣,クリトリス,淫乱,卑猥,風俗,売春,汚物,ハゲ,援交,デブ,黒人,白人,ハゲ,援助交際,部落,売春,ポルノ,アル中,キチガイ,きちがい,北鮮,支那,嫌い,オーバードーズ,れいわ,レイプ,殺害,死亡,重傷,重軽傷,訃報,亡くなる,死去,ロシア,アイヌ,ババア,ジジイ,おっぱい,お尻,乳首,陰茎,殺し,オカマ,乞食,制裁,チビ,クンニ,痴呆,北鮮,土方,未亡人,癩病,非人,糞,オナニー,中共,ニガー,土人,玉袋,強姦,チー牛,色盲,自閉,精神異常,ガイジ,マン毛,チン毛,障害者,北朝鮮,イスラエル,犯罪,火災,ガン,ちんk,まんk,うんk,なすきー,神罪,学タブ,生理,ブロック,ミュート,炎上,謝罪,燃やす,しばく,燃やしたい,しばきたい,810,アル中,114614,syamu,消えろ,野獣先輩,花魁,ヤクザ,マゾ,サド,ドM,ドS,クソ,鬱,躁,自◯,誹謗中傷,立花孝志,山本太郎,斎藤元彦,死去,自殺,遺書,ドヤコンガ,お気持ち,あほしね,不愉快,不快,オナ禁,不同意,性交,痴漢,腐す,中共,参政党,妄言,いい加減,コイツ,むかつく,SEX,近親相姦,セックス,自慰,飲精,イラマ,シックスナイン,BDSM,下品,堕胎,M女,AV,ジュニアアイドル,イメージビデオ,大物ユーチューバー,潤羽るしあ,ヘイト,ロリコン,ペドフィリア,キショい,通り魔,魔女狩,中国,アメリカ,トランプ,習近平,潰れて,つぶれて,くれメンス,フジテレビ,病気,湧いてる,おかしい,えっち,性的,反対,テロ,虐殺,ガザ,パレスチナ,ナチス,ADHD,ASD,アスペ,浮気,不倫,オッパイ,コロナ,インフル,ヤキ入れ,調子乗ってる,フツーに,罰,調子に乗ってる,WWWW,wwww,笑笑,在日,ルッキズム,MeToo,イーロン,面倒,ダルい,だるい,デブ,自傷,ジジイ,じじい,ババア,ばばあ,ペニス,アナル,おまんけ,耳垢,鼻くそ,うんこ,ぶりぶり,精液,みどら,ちんちん,]